package MacImport;

import Debug.*;
import Settings.Settings;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.LinkedList;

public class MacImport {

    /**
     * CSVToArray() takes a filepath to a csv file and returns its content as a two dimensional array
     */
    public Object[][] CSVToArray(@NotNull String filename) {

        String[] localarrayStringUnformated;
        String[][] localarrayString;

        int count = 0;
        LinkedList<String[]> content = new LinkedList<>();

        //Import CSV into a List of Arrays
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            while ((line = br.readLine()) != null) {
                content.add(line.split(Settings.csvFieldSeperator));
            }
        } catch (Exception e) {
            //Some error logging
            Debug.Log("Error loading CSV file",1, DEBUGTYPE.ERROR);
        }

        //Converting List to Array
        localarrayString = new String[content.size()][content.get(0).length];
        for (int i = 0; i < content.size(); i++) {
            System.arraycopy(content.get(i), 0, localarrayString[i], 0, content.get(0).length);
        }

        return localarrayString;
    }

    /**
     * parseMACfromArray() parses MACs from the two dimensional array generated by CSVToArray()
     */
    public LinkedList<String> parseMACfromArray(@NotNull String[][] localarrayString) {
        LinkedList<String> locallistString;
        locallistString = new LinkedList<>();

        //Take the third entry from each row and add it to a list
        for (String[] strings : localarrayString) {
            locallistString.add(strings[Settings.macColumn]);
        }

        return locallistString;
    }
}


