package MacImport;

import Debug.*;
import Settings.Settings;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Arrays;
import java.util.LinkedList;

public class MacImport {

    /**
     * CSVToArray() takes a filepath to a csv file and returns its content as a two dimensional array
     */
    public LinkedList<LinkedList<String>> CSVToLinkedList(@NotNull String filename) {

        int count = 0;
        LinkedList<LinkedList<String>> content = new LinkedList<>();

        //Import CSV into a List of Arrays
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            while ((line = br.readLine()) != null) {
                content.add(new LinkedList<>(Arrays.asList(line.split(Settings.csvFieldSeparator))));
            }
        } catch (Exception e) {
            //Some error logging
            Debug.Log("Error loading CSV file", 1, DEBUGTYPE.ERROR);
        }

        return content;
    }

    /**
     * parseMACfromArray() parses MACs from the two dimensional array generated by CSVToArray()
     */
    public LinkedList<String> parseMACfromLinkedList(@NotNull LinkedList<LinkedList<String>> locallistString) {

        LinkedList<String> returnlistString = new LinkedList<String>();

        //Take the third entry from each row and add it to a list
        try {
            for (LinkedList<String> strings : locallistString) {
                returnlistString.add(strings.get(Settings.macColumn));
            }
        }
        catch(Exception e)
        {
            Debug.Log("Mac Column is out of csv bounds", 0, DEBUGTYPE.ERROR);
        }
        return returnlistString;
    }
}


